[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vote = "3dVu4pTWwRJ8WMzG7aW196GiNjsBPFYDoy5uGw7PZw2J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/efe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
